### ISSUE TITLE
The type initializer 'Equ.MemberwiseEquatable'1' threw an exception

### ISSUE THREAD

**Issue by gasparnagy** [thedmi/Equ#20] opened 2019-07-23 08:52 UTC
Unfortunately I cannot reproduce this issue or get more details about it, but after rolling out my VS extension (Deveroom) with Equ, some users reported that they have received an error

```
The type initializer 'Equ.MemberwiseEquatable'1' threw an exception
```

See [related issue](https://github.com/specsolutions/deveroom-visualstudio/issues/45) at the Deveroom project.

The same assembly and the same classes deriving from `MemberwiseEquatable` works fine on most of the environments... My extension is compiled with .NET 4.6.1 so I guess the machine that produced the error had .NET Standard 1.5 available...

Do you have any idea how this could have happened?

**Comment by thedmi** [comment] 2019-07-23 09:24
Could be related to #9 , but it's difficult to say without more information. 

What I *can* say is that the equals and hash code functions are generated in a static context, and an issue there would produce the above exception. 

With the exact class definition it would be easy to reproduce the issue, as everything that happens there just relies on static information from the class.

**Comment by gasparnagy** [comment] 2019-07-23 10:21
@thedmi yeah, the funny thing for this issue that it is dependent on the environment, not on the class definition. With the same class it works on another machine. So it must be some missing framework dependency or security restriction... :( 
Feel free to close this issue, because I cannot give more info...

**Comment by thedmi** [comment] 2019-07-24 07:58
Closing due to lack of further information.

**Closed by thedmi** 2019-07-24 07:58 UTC
